DROP TABLE ACTIVITY CASCADE
DROP TABLE DIARYELEMENT CASCADE
DROP TABLE DIARYPIC CASCADE
DROP TABLE DIARYTEXT CASCADE
DROP TABLE ANOTIFICATION CASCADE
DROP TABLE TEXTNOTIFICATION CASCADE
DROP TABLE IMAGENOTIFICATION CASCADE
DROP TABLE PUSHMESSAGES CASCADE
DROP TABLE PROFILE CASCADE
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
